/// Flutter icons PuzzleIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PuzzleIcons
///      fonts:
///       - asset: fonts/PuzzleIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class PuzzleIcons {
  PuzzleIcons._();

  static const _kFontFam = 'PuzzleIcons';
  static const String? _kFontPkg = null;

  static const IconData watch = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vibration = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vibration_off = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movements = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dark_mode = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
